import assert from "node:assert/strict";
import { spawn, spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { setTimeout } from "node:timers/promises";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { resolveDeployment } from "./deploy-state.mjs";

const scripts = path.dirname(fileURLToPath(import.meta.url));
const root = path.dirname(scripts);
const app = { name: "pyxis", pid: 1, pm2_env: { pm_cwd: root, status: "online", NEXT_DIST_DIR: ".next-b" } };
const server = (dist = ".next-prod") => ({ cwd: root, args: ["node", "server.ts"], env: { NODE_ENV: "production", NEXT_DIST_DIR: dist }, children: [] });

test("reads the real server child, not stale PM2/yarn environment", () => {
  const processes = { 1: { cwd: root, args: ["node", "yarn", "start"], env: {}, children: [2] }, 2: server() };
  assert.deepEqual(resolveDeployment([app], "pyxis", root, (pid) => processes[pid]), { current: ".next-prod", target: ".next-a" });
  assert.deepEqual(resolveDeployment([app], "pyxis", root, () => server(".next-a")), { current: ".next-a", target: ".next-b" });
  assert.deepEqual(resolveDeployment([app], "pyxis", root, () => server(".next-b")), { current: ".next-b", target: ".next-a" });
});

test("refuses missing, ambiguous, stopped, or wrong-project apps", () => {
  assert.throws(() => resolveDeployment([], "pyxis", root), /exactly one/);
  assert.throws(() => resolveDeployment([app, app], "pyxis", root), /exactly one/);
  assert.throws(() => resolveDeployment([{ ...app, pid: 0 }], "pyxis", root), /not online/);
  assert.throws(() => resolveDeployment([app], "pyxis", "/another-project"), /another project/);
});

test("refuses unknown, missing, or development runtime builds", () => {
  assert.throws(() => resolveDeployment([app], "pyxis", root, () => server("../other")), /Unknown active/);
  assert.throws(() => resolveDeployment([app], "pyxis", root, () => null), /Cannot uniquely/);
  assert.throws(() => resolveDeployment([app], "pyxis", root, () => ({ ...server(), env: { NODE_ENV: "development" } })), /development server/);
});

const fakePm2 = `#!/usr/bin/env node
const fs=require('node:fs'),{spawn}=require('node:child_process');
const state=JSON.parse(fs.readFileSync('runtime.json','utf8'));
if(process.argv[2]==='jlist') {
 console.log(JSON.stringify([{name:'pyxis',pid:state.pid,pm2_env:{pm_cwd:process.cwd(),status:'online'}}]));
} else if(process.argv[2]==='restart') {
 process.kill(state.pid);
 const dist=process.env.NEXT_DIST_DIR;
 const child=spawn(process.execPath,['server.ts'],{cwd:process.cwd(),detached:true,stdio:'ignore',env:{...process.env,NODE_ENV:'production',NEXT_DIST_DIR:dist}});
 child.unref();
 fs.writeFileSync('runtime.json',JSON.stringify({pid:child.pid,dist}));
 fs.appendFileSync('restarts.log',dist+'\\n');
} else if(process.argv[2]!=='save') process.exit(1);
`;
const fakeYarn = `#!/usr/bin/env node
const fs=require('node:fs');
const active=JSON.parse(fs.readFileSync('runtime.json','utf8')).dist;
if(!fs.existsSync(active+'/BUILD_ID')) throw new Error('Serving build was moved before build');
fs.writeFileSync('build-tsconfig.json',fs.readFileSync('tsconfig.json'));
fs.writeFileSync('next-env.d.ts','generated by Next');
if(process.env.FAIL_BUILD) process.exit(1);
const target=process.env.NEXT_DIST_DIR;
const id='build-'+Date.now();
fs.mkdirSync(target+'/static/'+id,{recursive:true});
fs.writeFileSync(target+'/BUILD_ID',id);
fs.writeFileSync(target+'/static/'+id+'/_buildManifest.js','manifest');
`;
const fakeCurl = `#!/usr/bin/env node
const fs=require('node:fs');
const {dist}=JSON.parse(fs.readFileSync('runtime.json','utf8'));
if(process.env.FAIL_START && dist!=='.next-prod') process.exit(22);
const id=fs.readFileSync(dist+'/BUILD_ID','utf8');
const url=process.argv.at(-1);
if(url.includes('/_next/') && !url.endsWith('/'+id+'/_buildManifest.js')) process.exit(22);
console.log('200');
`;

async function fixture(t) {
  const dir = mkdtempSync(path.join(os.tmpdir(), "pyxis-deploy-test-"));
  for (const sub of ["scripts", "bin", "tmp", ".next-prod/static/old-build"]) mkdirSync(path.join(dir, sub), { recursive: true });
  for (const name of ["deploy.sh", "deploy-state.mjs"]) copyFileSync(path.join(scripts, name), path.join(dir, "scripts", name));
  for (const [name, content] of [["pm2", fakePm2], ["yarn", fakeYarn], ["curl", fakeCurl]]) writeFileSync(path.join(dir, "bin", name), content, { mode: 0o755 });
  const tsconfig = JSON.stringify({ include: ["**/*.ts", ".next-prod/types/**/*.ts", ".next-verify/types/**/*.ts"] });
  writeFileSync(path.join(dir, "tsconfig.json"), tsconfig);
  writeFileSync(path.join(dir, "next-env.d.ts"), "original next types");
  writeFileSync(path.join(dir, ".next-prod/BUILD_ID"), "old-build");
  writeFileSync(path.join(dir, ".next-prod/static/old-build/_buildManifest.js"), "old manifest");
  writeFileSync(path.join(dir, "server.ts"), "setInterval(() => {}, 1000);");
  const child = spawn(process.execPath, ["server.ts"], { cwd: dir, stdio: "ignore", env: { ...process.env, NODE_ENV: "production", NEXT_DIST_DIR: ".next-prod" } });
  writeFileSync(path.join(dir, "runtime.json"), JSON.stringify({ pid: child.pid, dist: ".next-prod" }));
  t.after(() => {
    const { pid } = JSON.parse(readFileSync(path.join(dir, "runtime.json"), "utf8"));
    try { process.kill(pid); } catch {}
    rmSync(dir, { recursive: true, force: true });
  });
  await setTimeout(40);
  function run(extraEnv = {}) {
    return spawnSync("bash", ["scripts/deploy.sh"], { cwd: dir, encoding: "utf8", timeout: 15000, env: { ...process.env, PATH: `${dir}/bin:${process.env.PATH}`, TMPDIR: `${dir}/tmp`, PM2_APP: "pyxis", PORT: "3001", DEPLOY_HEALTH_TIMEOUT: "1", ...extraEnv } });
  }
  function restored() {
    assert.equal(readFileSync(path.join(dir, "tsconfig.json"), "utf8"), tsconfig);
    assert.equal(readFileSync(path.join(dir, "next-env.d.ts"), "utf8"), "original next types");
  }
  return { dir, run, restored };
}

test("three successive deployments alternate releases and keep the active build intact", async (t) => {
  const f = await fixture(t);
  for (const target of [".next-a", ".next-b", ".next-a"]) {
    const result = f.run();
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.equal(JSON.parse(readFileSync(path.join(f.dir, "runtime.json"), "utf8")).dist, target);
    const config = JSON.parse(readFileSync(path.join(f.dir, "build-tsconfig.json"), "utf8"));
    assert.deepEqual(config.include, ["**/*.ts", `${target}/types/**/*.ts`, `${target}/dev/types/**/*.ts`]);
    f.restored();
  }
  assert.equal(readFileSync(path.join(f.dir, ".next-prod/BUILD_ID"), "utf8"), "old-build");
  assert.equal(readFileSync(path.join(f.dir, "restarts.log"), "utf8"), ".next-a\n.next-b\n.next-a\n");
});

test("build failure restores config without restarting the serving app", async (t) => {
  const f = await fixture(t);
  const result = f.run({ FAIL_BUILD: "1" });
  assert.notEqual(result.status, 0);
  assert(!existsSync(path.join(f.dir, "restarts.log")));
  assert.equal(readFileSync(path.join(f.dir, ".next-prod/BUILD_ID"), "utf8"), "old-build");
  f.restored();
});

test("unhealthy new server rolls back to the previous release", async (t) => {
  const f = await fixture(t);
  const result = f.run({ FAIL_START: "1" });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /Previous build restored/);
  assert.equal(readFileSync(path.join(f.dir, "restarts.log"), "utf8"), ".next-a\n.next-prod\n");
  f.restored();
});

test("a held deployment lock prevents a second build or restart", async (t) => {
  const f = await fixture(t);
  const lock = spawn("flock", [".deploy.lock", "node", "-e", "console.log('locked');setInterval(()=>{},1000)"], { cwd: f.dir, detached: true, stdio: ["ignore", "pipe", "inherit"] });
  t.after(() => { try { process.kill(-lock.pid); } catch {} });
  await new Promise((resolve) => lock.stdout.once("data", resolve));
  const result = f.run();
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /Another Pyxis deployment/);
  assert(!existsSync(path.join(f.dir, "build-tsconfig.json")));
});
